
name: Daily FTSO Report

on:
  workflow_run:
    workflows: ["pages build and deployment"]
    types:
      - completed

  workflow_dispatch:

jobs:
  run-agent-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run MCP Agent Pipeline
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECIPIENT_1: ${{ secrets.RECIPIENT_1 }}
          RECIPIENT_2: ${{ secrets.RECIPIENT_2 }}
        run: |
          echo "EMAIL_USER=$EMAIL_USER" > .env
          echo "EMAIL_PASS=$EMAIL_PASS" >> .env
          echo "SENDER_EMAIL=$SENDER_EMAIL" >> .env
          echo "RECIPIENT_1=$RECIPIENT_1" >> .env
          echo "RECIPIENT_2=$RECIPIENT_2" >> .env
          python -c "from agent_router import run_daily_pipeline; run_daily_pipeline()"
