name: GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read       # for checkout, build, etc.
  pages: write         # to push the Pages deployment
  id-token: write      # to mint the OIDC token for verification

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    # Skip deployment on pull request runs or from forks. Pull requests and
    # forked repositories do not have permission to publish Pages and would
    # cause the job to fail.
    if: ${{ github.repository == 'tripkane/flare-ftso-snapshot' && !github.event.pull_request }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

